### GET Skills
GET http://localhost:4004/spacefarers/Skills
Authorization: Basic alice:

### GET Skill by ID
GET http://localhost:4004/spacefarers/Skills(0efd6e5f-1811-499d-9924-c89699ac7dda)
Authorization: Basic alice: