
### Browse Spacefarers
GET http://localhost:4004/spacefarers/Spacefarers
Authorization: Basic alice:

### Get Spacefarer by ID
GET http://localhost:4004/spacefarers/Spacefarers(61be4551-5f87-43bf-b662-beb9c2c417d2)
Authorization: Basic alice:

### Create Spacefarer
POST http://localhost:4004/spacefarers/Spacefarers
Authorization: Basic alice:
Content-Type: application/json

{
	"first_name": "John",
	"last_name": "Doe",
	"birthday": "2085-01-12",
	"email": "john_doe@test.com",
	"position_ID": "bbf25b5e-738a-40a6-bb60-cb8365e58259",
	"department_ID": "abed6ac3-2193-4898-b6a8-8b8d8e331f58",
	"origin_planet_ID": "55929c45-9f7c-49cd-9f05-35848d9f98d1"
}

### Delete Spacefarer
DELETE http://localhost:4004/spacefarers/Spacefarers(61be4551-5f87-43bf-b662-beb9c2c417d2)
Authorization: Basic alice:
